version: '3'
services:
  test:
    build:
      context: test
      dockerfile: Dockerfile
    volumes:
      - .:/sys-sage
    working_dir: /sys-sage
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_BUILD_TYPE=Debug -DPAPI=ON
        cmake --build build --parallel
        cmake --install build --prefix /usr
        cmake -S test -B test/build -DCMAKE_BUILD_TYPE=Debug
        cmake --build test/build --parallel
        ./test/build/test
        python3 -m venv python/venv
        python/venv/bin/python -m pip install ./python
        python/venv/bin/python test/topology.py
        python/venv/bin/python test/relation.py
        python/venv/bin/python test/datapath.py
